name: Copy and Replace

on:
  push:
    branches:
      - cvpr2024

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and extract CVPR-2024-main
        run: |
          curl -L https://github.com/cvpr-org/author-kit/archive/refs/tags/CVPR2024-v2.tar.gz -o CVPR2024-v2.tar.gz
          tar -xf CVPR2024-v2.tar.gz
          rm CVPR2024-v2.tar.gz
          mv author-kit-CVPR2024-v2/ CVPR-2024-main

      - name: Clone ml-paper-template
        run: |
          git clone https://github.com/apoorvkh/ml-paper-template.git

      - name: Copy contents from CVPR 2024
        run: |
          cp -r CVPR-2024-main/sec ml-paper-template/
          cp -f CVPR-2024-main/main.tex ml-paper-template/
          cp -f CVPR-2024-main/cvpr.sty ml-paper-template/_packages.tex

      - name: Rename original cvpr conference file 
        run: mv CVPR-2024-main/main.tex CVPR-2024-main/cvpr_template.tex

      - name: Render PDF cvpr2024
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: CVPR-2024-main/cvpr_template.tex

      - name: Rename original ml-paper conference file 
        run: mv ml-paper-template/main.tex ml-paper-template/ml_template.tex
      
      - name: Render PDF ml-paper
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: ml-paper-template/ml_template.tex  

      - name: Convert PDF to PPM
        run: |
          pdftoppm -jpeg -r 300 CVPR-2024-main/cvpr_template.pdf output
          pdftoppm -jpeg -r 300 ml-paper-template/cvpr_template.pdf output_temp

      - name: Compare images
        run: |
          for i in $(seq 1 5); do
            magick compare output-${i}.jpg output_temp-${i}.jpg diff_${i}.jpg
          done


